### ISSUE TITLE
Avoid overlapping of labels of oriented edges between the same two nodes

### ISSUE THREAD

**Issue by humbertmason** [graphstream/gs-core#103]
Hello,

I would like to use your library because I find it very well written, but I have a problem which I am unable to solve.

I have an weighted oriented graph which should represent a social network. My network could have symmetric relations between the same nodes, so there could be an edge from a node A and a node B and an edge from a node B to a node A. I should show these two edges as distinct ones, and each of the two edges should have an own different label representing its weight. My problem is that I don't know how to avoid overlapping between the labels of the two edges.

I have written a simple toy application to show my problem:

```
public class Application
{
    public static void main(String [] args)
    {
        System.setProperty("org.graphstream.ui.renderer", "org.graphstream.ui.j2dviewer.J2DGraphRenderer");

        MultiGraph graph = new MultiGraph("Network");

        graph.addAttribute("ui.quality");
        graph.addAttribute("ui.antialias");
        graph.addAttribute("ui.stylesheet", "edge {text-alignment: along;}");

        graph.addNode("A");
        graph.addNode("B");

        Edge ab = graph.addEdge("AB", "A", "B", true);
        Edge ba = graph.addEdge("BA", "B", "A", true);

        ab.setAttribute("ui.label", "1.2345");
        ba.setAttribute("ui.label", "5.4321");

        graph.display();
    }
}
```

My output looks like this:
![overlapping](https://f.cloud.github.com/assets/6094415/1662902/fa40554a-5c07-11e3-80e7-ec416c5d0f78.png)

I would like an output like this:
![notoverlapping](https://f.cloud.github.com/assets/6094415/1662904/07512caa-5c08-11e3-900f-69c8e2349914.png)

...or something similar.

Please, how could I solve this problem? I would love to use your library, but I need to solve this problem first.

Thank you very much.

**Comment by rishier827** [comment]
> ab.setAttribute("ui.style", "text-offset: -100, -200;");

for randomly generated ones then how can we adjust it

**Comment by 1135789582** [comment]
Hello, I also have the problem of overlapping labels.  
Here is the version I used, Is there any good solution to this problem
![image](https://user-images.githubusercontent.com/44797651/108292540-3669bb80-71cf-11eb-8cdb-c0382dad44ef.png)

**Comment by 1135789582** [comment]
> 你好，
> 
> 我几乎解决了在连接相同节点的边缘上设置text-offset属性的问题。
> 
> 谢谢 ;）

I would like to ask how you solve this problem?
