### ISSUE TITLE
Element returned by View.findNodeOrSpriteAt() miss several attributes.

### ISSUE THREAD

**Issue by adriantirea** [graphstream/gs-core#114]
The findNodeOrSpriteAt() returns an element that has label and position attributes, but no one of other attributes.
Problem is present in  current gs-core nightly build. Note that gs-core 1.2 returns an element that contains all the attributes of that node.

**Comment by pigne** [comment]
`findNodeOrSpriteAt` returns a `GraphicElement`, not an actual graph `Element` (like `Node`). It's a lightweight version of the node. You'll have to get the node from the graph (`getNode()`) based on this id in order to get the actual node. 
Yes, the behavior is different from v 1.2.
