### ISSUE TITLE
Edge Rejected

### ISSUE THREAD

**Issue by engsoon89** [graphstream/gs-core#131]
Hi,

I got this error (below) when trying to generate a SingleGraph, with about 46k nodes.

"Edge 3549--3356[3549--3356] was rejected by node 3549"

I suppose this is caused by the "EdgeRejectedException", and I checked through to make sure all duplicated edge are filtered out, making sure that connected nodes are not re-added with the same edge. 

<code>
if(graph.getEdge(id) == null)
graph.addEdge(id, data[i-1], data[i]);
</code>

**Comment by mack007liu** [comment]
I also encountered the same problem
