### ISSUE TITLE
Provide a "real" -core package -- no GUI elements at all

### ISSUE THREAD

**Issue by fge** [graphstream/gs-core#135]
I would be interested in using this library for one of my projects, except that I don't need, or want, any GUI in any way, shape or form.

Is there a plan to strip core of any GUI components?

**Comment by pigne** [comment]
The version of the gui included in the core is minimal and we like the idea of having a minimal (core) library that provides a `Graph.display()` method. 

You can still remove anything you want from the jar files though. 

In a folder containing the core jar file (say `gs-core-1.2.jar`) just do:
```bash
❯ jar xf gs-core-1.2.jar
❯ rm -rf org/graphstream/ui
❯ jar cf trimmed-gs-core-1.2.jar META-INF org
```
This will work provided you don't try to call `Graph.display`. 

That said, you just spared a couple hundred Kilobytes:
```bash
❯ du -hs trimmed-gs-core-1.2.jar gs-core-1.2.jar                                                                       ⏎
620K	trimmed-gs-core-1.2.jar
868K	gs-core-1.2.jar

**Comment by fge** [comment]
Hold on. I have not looked at dependencies in detail. -core depends on two libraries. What do these libraries do?

If they hande GUI stuff, that is all the more you have to add to the package...
