### ISSUE TITLE
Save graph and edge attributes

### ISSUE THREAD

**Issue by pietrodemu** [graphstream/gs-core#136]
I need to save a graph in a type file "Graphviz Dot", i.e.: nodes, edges, node attributes, edge attributes. I usually do in this way to save my graph in the file:

```java
Graph graph = new MultiGraph(strId, strictChecking, autoCreate);
String filePath = "graph.dot";
// create nodes, edges, node attributes, edge attributes...
FileSinkDOT fs = new FileSinkDOT();
fs.writeAll(graph, filePath);
```

Problem: When I open or load the file "graph.dot", I can't see edge attributes. Anyone knows can I save this file?

Thank you for all your assistance.

**Comment by Augustin-Zidek** [comment]
I have the same problem. Even if I add an attribute to every edge (i.e. `edge.addAttribute("color", "gray")`) doesn't work.

**Comment by gsavin** [comment]
Actually, this is not possible, when using the dynamic way to output a graph, to include edge attributes. But I added a fix to output the attributes when using the ``writeAll`` method. It should work now.
