### ISSUE TITLE
Sinks, SpringLayout write into stdout or stderr

### ISSUE THREAD

**Issue by Augustin-Zidek** [graphstream/gs-core#138]
Various sinks write directly into System.out or System.err. It would be useful if these sinks provided a OutputStream parameter (or some kind of a log), into which they would write their debug info.

**Comment by gsavin** [comment]
Most of the classes use the logging components of Java so you can add a new handler to redirect ouput. If some sinks have been forgotten, please name it.
Thanks.

**Comment by Augustin-Zidek** [comment]
TikZFileSink: "% [warning] units PX are not compatible with TikZ."
SpringBox: "layout.SpringBox.gravity: 0.040000"
PNGFileSink: "[s[K0 images written[u"

**Comment by gsavin** [comment]
``SpringBox`` already uses the logging components. I fixed the others.
