### ISSUE TITLE
ui.selected attribute not set for edges

### ISSUE THREAD

**Issue by beaujest** [graphstream/gs-core#140]
I modified Tutorial1 in your examples to use the VerboseSink:
```java
public class Tutorial1 {
	public static void main(String args[]) {
		Graph graph = new SingleGraph("Tutorial 1");
		Viewer viewer = graph.display();
	
		// Some events:
		graph.addNode("A");
		graph.addNode("B");
		graph.addEdge("AB", "A", "B");
		graph.addNode("C");
		graph.addEdge("BC", "B", "C", true); // Directed edge.
		graph.addEdge("CA", "C", "A");
		
		ViewerPipe viewPipe = viewer.newViewerPipe();
		viewPipe.addSink(new VerboseSink());
		viewPipe.pump();
		
		while (true) {
			viewPipe.pump();
		}
	}
}
```
When I make a selection that includes node A and B, I see the following in the Console:
>[GraphicGraph_3515:28] set node "A" +"ui.selected"=true
>[GraphicGraph_3515:29] set node "B" +"ui.selected"=true

I would also expect edge AB to have it's ui.selected attribute set to true.

**Comment by pigne** [comment]
In doubt that. Only nodes and sprites get selected by [DefaultMouseManager](https://github.com/graphstream/gs-core/blob/master/src/org/graphstream/ui/view/util/DefaultMouseManager.java). No Edges.

**Comment by beaujest** [comment]
Ok, thanks for the response.  I'd suggest updating the documentation, as it indicates otherwise- http://graphstream-project.org/doc/Tutorials/GraphStream-CSS-Reference_1.0/#events

**Comment by pigne** [comment]
Thanks for the suggestion. I updated the doc.
