### ISSUE TITLE
DefaultCamera without metrics

### ISSUE THREAD

**Issue by hkhf12** [graphstream/gs-core#143]
Hello,

I try to use the Method DefaultCamera.findNodeOrSpriteAt(GraphicGraph graph, double x, double y), but I never get a node or sprite. I think the problem ist that the metrics of my DefaultCamera aren't correctly. I get the instance as follows:

view = viewer.addDefaultView(false);
ggraph = viewer.getGraphicGraph();
dcamera = new DefaultCamera(ggraph);

If i use view.getCamera() the metrics are right, but in the class Camera there is no method findNodeOrSpriteAt.

Thanks!

Best regards
Heiko K

**Comment by gsavin** [comment]
Camera is an object that needs to be updated by a view. That's why metrics are wrong when you create one outside the view.
But the method ``findNodeOrSpriteAt(...)`` is directly available in ``View`` if you are using a recent snapshot of GraphStream.

Cheers
