### ISSUE TITLE
Graph attributes not written to when graph is serialised to DOT format.

### ISSUE THREAD

**Issue by bevankoopman** [graphstream/gs-core#144]
When serialising a SingleGraph it seems that edge attributes are not persisted in the output .dot file. Sample code to reproduce:

```
SingleGraph g = new SingleGraph("G", false, false);

g.addNode("A");
g.addNode("B");
		
Edge e = g.addEdge("AB", "A", "B");
e.addAttribute("edgeWeight", 1.0);

g.write("g.dot");
```

It seems that `org.graphstream.stream.file.FileSinkDOT:edgeAttributeAdded(String graphId, long timeId, String edgeId, String attribute, Object value)` has not been implemented.

**Comment by gsavin** [comment]
Seems to be the same than #136 
You should use the last nightly build.
