### ISSUE TITLE
New maintenance release

### ISSUE THREAD

**Issue by castarco** [graphstream/gs-core#146]
Hello, I've seen that the latest released version of `gs-core` was launched in 2013, and we're in 2015. Maybe it's a good idea to release a new version, even if it hasn't all the features the team want to pack in the new and shinning version.

The reason why I'm saying this is because dependencies versions, using graphstream makes project dependencies to be "dirty" (for example with JUnit), and because I've also seen that there's active development (not much, but something).

**Comment by pigne** [comment]
Hi. I concur, you made a valid point here. Although development as been pretty slow, many bug fixes have been committed to the dev branch.  Plus, dependencies could be updated.

**Comment by gsavin** [comment]
Hi, v1.3 has been released today to make fixes from these last... two years more "official".
Thanks for your advice.
