### ISSUE TITLE
Text-Alignment Not Working !!!

### ISSUE THREAD

**Issue by MostafaGamal** [graphstream/gs-core#147]
Hello,

When i use text-alignment: left or right or anything else ...
the text is always at right of the node !

i don't know why or what is the problem

Working with Version 1.3

**Comment by gsavin** [comment]
Hi,
Just include le gs-ui module in your project and add
``System.setProperty("gs.ui.renderer", "org.graphstream.ui.j2dviewer.J2DGraphRenderer");``
before the display method call.
