### ISSUE TITLE
rotating the view to get a z-axis view

### ISSUE THREAD

**Issue by zcaudate** [graphstream/gs-core#157]
I'm trying to create a 3d axis with graphstream and although there is a z-axis coordinate, it seems like i can only rotate in the x-y plane

<img width="325" alt="screen shot 2015-07-27 at 5 51 39 pm" src="https://cloud.githubusercontent.com/assets/1455572/8905972/291f6ce8-3488-11e5-8f14-0ea766002996.png">

Should I give up or is there another way for visualizing 3d data.

**Comment by pigne** [comment]
2d only. Sorry.
