### ISSUE TITLE
Graph Stats

### ISSUE THREAD

**Issue by Ceceu** [graphstream/gs-core#165]
Hi,

Is there a way to mesure Krackhardt’s connectedness and others graph scores like vertex degree average?

Krackhardt’s connectedness: http://www.analytictech.com/mgt780/2008/slides/graphcohesion.pdf
PAGE: 15

Thanks, Celso.

**Comment by ThibautDemare** [comment]
Hi,

You can find some algorithms to make measures on graphs in the gs-algo package (including the "averageDegree(Graph graph)" method in the or.graphstream.algorithm.Toolkit).
However, I don't remember of a method about the Krackhardt’s connectedness. But according to the formula you gave, it seems easy to implement it.

Thibaut

**Comment by Ceceu** [comment]
Hello Thibaut
Thank you so much and congratulation for you work.
LLAP
Celso França





Date: Mon, 18 Jan 2016 02:15:47 -0800
