### ISSUE TITLE
Export a graph

### ISSUE THREAD

**Issue by tvejar** [graphstream/gs-core#166]
Once I have done the graph, how can I export it?

**Comment by tvejar** [comment]
why don't you answer my question? :(

**Comment by gsavin** [comment]
The main role of "issues" should be to post issue. You can use the mailing list if you have some questions to which you can not find answer in the documentation.

You can export a graph using any `FileSink*` object. Or you can directly use the `Graph.write(path)` method, it should detect the format using the file extension and use the appropriate file sink.

**Comment by tvejar** [comment]
Ok, thanks!
