### ISSUE TITLE
Docs under Zoom and Panning does not match 1.3 release package

### ISSUE THREAD

**Issue by aarthipa** [graphstream/gs-core#168]
Hi,
I'm referring to the link below to enable zoom on my graph
http://graphstream-project.org/doc/Tutorials/Graph-Visualisation/1.0/#zooming-and-panning

In the following lines, I imported Viewer from org.graphstream.ui.swingViewer.Viewer
Viewer viewer = graph.display(false);
View view = viewer.getDefaultView();
view.resizeFrame(800, 600);
view.setViewCenter(440000, 2503000, 0);
view.setViewPercent(0.25);

However, there is no "viewer" class (supposed to be under org.graphstream.ui.swingViewer.Viewer) in the 1.3 release of gs-core
Instead if I import org.graphstream.ui.view.Viewer,  there is no "setViewCenter" and "setViewPercent" methods.
Please let me know which class to import.

**Comment by gsavin** [comment]
`Viewer` moved to `org.graphstream.ui.view` since last release. We want to have a generic definition of the viewer, independent of AWT/Swing. Documentation has not been updated yet.

`setViewCenter` and `setViewPercent` are method of `Camera`, which you can get with `View.getCamera()`.
