### ISSUE TITLE
Certification Error of http://graphstream-project.org/

### ISSUE THREAD

**Issue by koyamalmsteen** [graphstream/gs-core#169]
Steps: 
`<project name="Sample">
<target name="Sample">
<get src="https://data.graphstream-project.org/graphstream/gs-core/zip/1.3" dest="/tmp/test" />
</target>
</project>`

Problem: 
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Notes:
To fix the httpd-ssl.conf on http://graphstream-project.org/.

**Comment by gsavin** [comment]
Certificate has been provided by Let's Encrypt which uses a fresh new root certificate that some people does not have yet on their system as trusted CA. Maybe you are in such a case.
