### ISSUE TITLE
OutputType enums were renamed but not reflected in documentation

### ISSUE THREAD

**Issue by CheriePun** [graphstream/gs-core#175]
I believe the enums were renamed some time ago and the documentations were not updated to reflect the change.
Code:
https://github.com/graphstream/gs-core/blob/eb71c7dc7862eb8284f194c7b86b9a7d5a3dc678/src/org/graphstream/stream/file/FileSinkImages.java#L189
Doc:
http://graphstream-project.org/doc/Tutorials/Creating-a-movie-with-FileSinkImages/

**Comment by gsavin** [comment]
I guess you are talking about `OutputPolicy`, not `OutputType`. So yes, there is an update problem here. output policies were renamed to upper case. It's fixed now.
Thanks.

**Comment by CheriePun** [comment]
Yes, that's what I meant to write. Thanks for fixing it.
