### ISSUE TITLE
Keys values in exported graphs

### ISSUE THREAD

**Issue by 0pipe0** [graphstream/gs-core#181]
Hi, I've seen that the value of the key's attribute in exported graphs files are "attrxxxx". Is that a normal behaviour? I'm exporting in graphml, so I modified FileSinkGraphML.java just for testing purpose:

(For Nodes and Edges attributes)
`--  String id = String.format("attr%04X", attribute++);
++ String id = String.valueOf(k);
`

now `.addAttribute("test","test__")` results  
`<data key="test">test__</data>` and no more `<data key="attr0000">test__</data>`.
Is this the right way or attrxxxx format is the way you have choosen to show keys values?

Thanks.
Licio.

**Comment by pigne** [comment]
According the the [GraphML specification](http://graphml.graphdrawing.org/specification.html), attributes' keys need to be defined with a `<key>`  attribute. Check the header of you file, you will find the definition of the key. Something like :

```xml
<key id="attr0000" for="node" attr.name="test" attr.type="string"/>
```

then the `id` of the key is used when defining new data values. So, yes it is the right way.
