### ISSUE TITLE
Blank view

### ISSUE THREAD

**Issue by PlayMa256** [graphstream/gs-core#184]
Well, i have the following scenarios:

 - A Java class that extends JFrame instantiating the other class that
   contains my graph which returns a blank screen.

 - The second a normal class with the method main inside of it, calling
   the same class that contains my graph which returns a normal graph.

Now, why the class that is a JFrame returns a blank graph?

My code of the graph class.

    public class grafoComparacao implements ViewerListener {
        private List<Comparados> integralizacoesComparadas;
        private Viewer viewer;
        private Graph graph;
        private View view;
        protected boolean loop = true;
            
        public grafoComparacao(List<Comparados> listaComparados) throws HeadlessException, InterruptedException {
            System.setProperty("org.graphstream.ui.renderer", "org.graphstream.ui.j2dviewer.J2DGraphRenderer");
            this.integralizacoesComparadas = listaComparados;
            graph = new MultiGraph("clicks");
            graph.addAttribute("ui.stylesheet", GraphsStreamStylesheet.stylesheet);
    
            adicionaNodes(graph);
            
            viewer = new Viewer(graph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
            viewer.enableAutoLayout();
            view = viewer.addDefaultView(false);
            
            JFrame frame = new JFrame("Comparação de catálogos");
            frame.add((Component) view);
            frame.setExtendedState(JFrame.MAXIMIZED_BOTH); 
    
            ViewerPipe fromViewer = viewer.newViewerPipe();
            fromViewer.addViewerListener(this);
            fromViewer.addSink(graph);
            
            frame.setVisible(true);
    
            while(loop) {
                fromViewer.pump();
            }        
        }
        
        //this actually works too.
    //    public static void main(String[] args) throws HeadlessException, InterruptedException{
    //        Control.Controller ctrl = new Controller();
    //        JFileChooser escolherAlunos = new JFileChooser();
    //        escolherAlunos.setMultiSelectionEnabled(true);
    //        escolherAlunos.showOpenDialog(null);
    //        File[] integralzacoes = escolherAlunos.getSelectedFiles();
    //        List<Comparados> integralizacoesComparadas = ctrl.geraComparacaoIntegralizacoes(integralzacoes);
    //        try {
    //            grafoComparacao comparacao = new grafoComparacao(integralizacoesComparadas);
    //        } catch (HeadlessException ex) {
    //            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    //        } catch (InterruptedException ex) {
    //            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    //        }
    //        new grafoComparacao(integralizacoesComparadas);
    //    }
        
        @Override
        public void viewClosed(String string) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    
        @Override
        public void buttonPushed(String string) {
            
        }
    
        @Override
        public void buttonReleased(String string) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    
        private void adicionaNodes(Graph graph) {
           //function that populate my graph
        }
        
    }

Here's where i call it.
       try {      
            grafoComparacao comparacao = new grafoComparacao(integralizacoesComparadas); // heres the graph call.
        } catch (HeadlessException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

When the class is a JFrame, the view just goes blank, when its a normal class and i'm running from the main, it works. What is the problem?
It doesnt throw any exception.

**Comment by PlayMa256** [comment]
After some debugging i discovered its a thread problem, it keeps happening even though changing the threading mode. If i remove the while on the viewerpipe.pump, the graph renders but stop woking the user interaction. I used all the thread methods but it still not rendering with the while there.

**Comment by gsavin** [comment]
Please, *issues* is used to submit issues, not personal programmation problem. Mailing-list is here to get some help from the community, if someone can or want to give you a reply.

The Swing thread can not do its rendering job if the thread is blocked inside a `while` loop.

**Comment by PlayMa256** [comment]
Well, that mailing list is kinda dead. I've put my graph class inside a swingworker already, but the user interaction is not working anymore.
