### ISSUE TITLE
j2viewer does not dissplay all css values

### ISSUE THREAD

**Issue by Rapso** [graphstream/gs-core#185]
Hi i have simple program with such css`" node { fill-mode: dyn-plain; size: 20px; text-mode: normal; text-size: 15px; text-style: bold; text-background-mode: rounded-box; text-color: #EB2; text-alignment: along;} edge { fill-mode: dyn-plain; size: 3px;} ")` while Text size, style, color are changed acording to css, the background-mode alignment is not changed. How it coudl be fixed?

**Comment by pigne** [comment]
You are probably not using the proper viewer : 

http://graphstream-project.org/doc/FAQ/The-graph-viewer/Why-CSS-property-X-does-not-work/
