### ISSUE TITLE
Found unreachable code

### ISSUE THREAD

**Issue by jycamus90** [graphstream/gs-core#187]
Hi, 

While going through the code, I found out that there is unreachable code in [line 151](https://github.com/graphstream/gs-core/blob/master/src/org/graphstream/ui/layout/springbox/implementations/SpringBoxNodeParticle.java#L151) and [line 191](https://github.com/graphstream/gs-core/blob/master/src/org/graphstream/ui/layout/springbox/implementations/SpringBoxNodeParticle.java#L191) in [SpringBoxNodeParticle.java](https://github.com/graphstream/gs-core/blob/master/src/org/graphstream/ui/layout/springbox/implementations/SpringBoxNodeParticle.java). 

The if branch in line 146 checks whether _len_ is bigger than 0. Then there's another if branch that checks whether _len_ is smaller than _box.k_ which is 1 by default. If _len_ is smaller than 1, then 1 will be assigned to _len_. If _len_ is bigger than 1, then the value of _len_ will be retained. However, in the following line, there's a ternary operator that checks whether _len_ is non-zero or not. Considering that _len_ will be greater than or equal to 1 after the second if branch, the second expression(0.00001) in the ternary operator will never get reached. 

If you don't mind, I would like to request a pull. It would be just changing the line 151 and 191 to 
`double factor = ((box.K2 / (len * len)) * node.weight);` 
I'm a first year PhD student in UCI and I'm taking a course this quarter where I can get extra credit from contributing to one of the popular open source software developments.

**Comment by pigne** [comment]
Hi, 

Indeed that's a bit of dead code. You'r welcome to submit a PR. 

Go get that extra credit!
