### ISSUE TITLE
Wrong arrow position when using shape:pie-chart on nodes

### ISSUE THREAD

**Issue by locchi93** [graphstream/gs-core#192]
When I set the nodes to have "shape:pie-chart;", the arrows of the directed edges are displayed incorrectly, it's like if they follow a square border. I do not know if I'm doing something wrong, but could not find anything about it. With "shape:circle;" all works fine.

![example](https://cloud.githubusercontent.com/assets/13962082/15587080/d6c6d360-2387-11e6-920e-8aa5d00cd59b.PNG)
![example](https://cloud.githubusercontent.com/assets/13962082/15600530/c82c11e0-23ea-11e6-8d78-2dd5e6bcd2f2.PNG)

**Comment by pigne** [comment]
This should be fixed now. 

Now if you need it, you'll have to [build the library using maven](http://graphstream-project.org/doc/Tutorials/GraphStream-Maven/#building-graphstream-using-maven).  Be sure to use branch `1.x` on both projects `gs-core`and `gs-algo`  (`gs-algo` too if you use it). this should give you `gs-core-1.3.1-SNAPSHOT.jar` and `gs-ui-1.3.1-SNAPSHOT.jar` that you can use in your project.
