### ISSUE TITLE
Node with 1 self-directed edge

### ISSUE THREAD

**Issue by mirkara** [graphstream/gs-core#195]
I would like to draw 1 node with 1 directed edge that points back to the node. Below are screenshots of attempts I've made. Does anyone know how to draw this cleanly? Note: there maybe more than 1 edge that exits & leaves the same node.

Using System.setProperty("org.graphstream.ui.renderer", "org.graphstream.ui.j2dviewer.J2DGraphRenderer"); 
https://i.stack.imgur.com/NpchS.png

Without using that system property
https://i.stack.imgur.com/vOrXC.png

Using v1.3 of gs-ui, and gs-core

**Comment by gsavin** [comment]
This is the `issues` part of the project, and so this is used to post issues. To ask for help you should use stackoverflow (as you have already done [here](http://stackoverflow.com/questions/38133904/visualization-one-node-multiple-edges) I guess) or the mailing list.
