### ISSUE TITLE
working with regions

### ISSUE THREAD

**Issue by hamedmohammadi** [graphstream/gs-core#196]
how about working with region that made by several nodes like coloring regions

**Comment by hamedmohammadi** [comment]
sry i know thats not a bug i'm glad to know about possibility

**Comment by hamedmohammadi** [comment]
thank for your trying to answer dude .anyway anyone can push a button ;).good luck

**Comment by gsavin** [comment]
Get you and another user mixed up. I was saying to him just a few time before your post that issues is dedicated to issues and the user mailing list is available to ask for help. You should easily find the "Get Some Help" section on the home page of the [website](http://graphstream-project.org/).
