### ISSUE TITLE
BarabasiAlbertGenerator generates more nodes than given

### ISSUE THREAD

**Issue by linghui2016** [graphstream/gs-core#197]
I used the given example to generate 10 nodes, but 12 nodes were generated, always two nodes more.

Graph graph = new SingleGraph("Barabàsi-Albert");
// Between 1 and 3 new links per node added.
Generator gen = new BarabasiAlbertGenerator(3);
// Generate 100 nodes:
gen.addSink(graph); 
gen.begin();

for(int i=0; i<100; i++) {
	gen.nextEvents();
}

gen.end();
graph.display();

**Comment by gsavin** [comment]
The count of `nextEvents()` call is not necessarily the count of nodes. It just means that the generator will do another step in its generation.

For BarabasiAlbert, the generator creates a first couple of nodes, that's why you are getting 10 + 2 nodes.

**Comment by linghui2016** [comment]
Thank you for the answer.  So you meant the generator creates first 2 nodes or it can be more? If i want to generate just 10 nodes, i just need to call the nextEvents() method for 8 times, am I understanding it right?

**Comment by gsavin** [comment]
That's it. Calling `nextEvents` 8 times, will give you 10 nodes. `n` times will give you `n+2` nodes.

**Comment by sbalev** [comment]
Or

```java
while (graph.getNodeCount() < desiredCount) {
    gen.nextEvents();
}
```

**Comment by linghui2016** [comment]
Thanks, then i think you should correct the tutorial.
However, you guys are doing really great work! i use graphstream for simulating distributed algorithms and it helps a lot!
