### ISSUE TITLE
LGPL or GPL?

### ISSUE THREAD

**Issue by dk1844** [graphstream/gs-core#200]
Hello, 

I'd like to ask you if you could clarify the licence state of GraphStream project, because I am a bit confused.

The release (let's say the current 1.3) includes 
* ``gs-core``,
* ``gs-ui``,
* and ``gs-algo``.

The first two seem to be dual-licenced under LGPL and/or CECILL-C (the readme file says so and both licences are attached).

But as for ``gs-algo`` - I am confused - the readme file says _GPLv2_, but instead licences LGPL and CECILL-C are attached. So, what is the intention and what is the mistake? Do you intend to provide the same license for all packages and just the readme is wrong? Or is it the other way around?

I'd like to try to use the project in my application, however I cannot use GPL (copyleft, and other lic. incompatibility), however LGPL would suit my needs fine.

Could you please clarify this conundrum for me?

With kind regards, 

Daniel

**Comment by pigne** [comment]
Hi, 

The Readme is wrong. GraphStream (`gs-core`, `gs-ui`, `gs-algo`) is indeed published under  both LGPL and CECILL-C licenses. No GPL. 

The file should be fixed now. 

Regards,
Yoann

**Comment by dk1844** [comment]
Great, thanks!
