### ISSUE TITLE
Remove Edge when a Node has a define attribute.

### ISSUE THREAD

**Issue by Nolyurn** [graphstream/gs-core#203]
I'd like to know why this

```java
for(Node n:graph){
	for(Edge e:n){
		if(!n.hasAttribute("toto")){
			graph.removeEdge(e);
		}
	}
}
```

Doesn't work, it remove some edges, but not every edges concerned.

**Comment by ThibautDemare** [comment]
Could you provide a full code to test this please?

**Comment by sbalev** [comment]
It's normal. Iterators on graph elements behave as specified [here](https://docs.oracle.com/javase/7/docs/api/java/util/Iterator.html#remove()).

> The behavior of an iterator is unspecified if the underlying collection is modified while the iteration is in progress in any way other than by calling this method.

The right way to do what you want would be something like this:

```java
for (Node n : graph)
    if (!node.hasAttribute("toto")) {
        Iterator<Edge> it = n.getEdgeIterator();
        while (it.hasNext()) {
            it.next();
            it.remove();
        }
    }
```

**Comment by Nolyurn** [comment]
Thanks for the answer :)
