### ISSUE TITLE
NullPointer wenn closing Viewer

### ISSUE THREAD

**Issue by jordilaforge** [graphstream/gs-core#207]
Hello Guys

Thank you for this awesome library. I have built a javafx application which shows relations between persons. Therefore I use a SwingNode to place the graph inside the application. To quit the swing graphstream thread I call the viewer.close method. (otherwise the thread will still be running after I close my javafx application). And there I have a problem sometimes while quiting the graphstream thread I get the following NullPointer:
`java.lang.NullPointerException
at org.graphstream.ui.view.Viewer.actionPerformed(Viewer.java:542)
at javax.swing.Timer.fireActionPreformed(Timer.java:313)
at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java. awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
etc...`
I think the Problem lies here: Viewer.java
`line: 542 boolean changed = graph.graphChangedFlag();`
It looks like graph.graphChangedFlag() can be null shouldn't there be a null check (null safe)?
Or is there another solution i missed? or am I doing something very wrong here?
Thank you a lot.

**Comment by pigne** [comment]
Would it be possible to propose a gist with a reproductible minimal example?

**Comment by jordilaforge** [comment]
Thats exactly the problem it just happens sometime but maybe i can put something together after work to show the problem..

**Comment by jordilaforge** [comment]
viewer = new Viewer(graph, ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
Seems to fix my problem no more null pointerss. Had it on GRAPH_IN_GUI_THREAD

**Comment by jordilaforge** [comment]
https://github.com/jordilaforge/GraphStreamNullPointerFX

Made a quick project to show my point i use a swing node to show the graph in a new stage in javafx. After I close the stage i need to quit all awt threads from graphstream therefore I use the viewer.close() method.

**Comment by pigne** [comment]
Thank you. Ok so the short and obvious answer, that you may already know, is that GraphStream wasn't build for, and is not compatible with JavaFX. 

Now, the `SwingNode` class helps but ui-related GraphStream stuff still needs to run in the Swing "event dispatcher" thread. 

As far as I understand we could wrap GS code with `SwingUtilities#invokeLater` calls and be safe from exception:

```java
  SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
          viewer.close();
      }
  });
```
but then the refresh/repaint would not be deterministic plus I don't know how the Swing process would stop when all JFX windows are closed.

**Comment by jordilaforge** [comment]
Hey pigne thank you for your input so with this the viewer is closed on the event dispatcher thread wich is obvious better than to close it from somewhere else thank you. What do you mean with refresh or repaint would not be deterministic? Is ther FX support planned in the future?

**Comment by pigne** [comment]
If you try the example you'll notice that sometimes (it looks random to me) the graph does not appear on the window however it is properly initialised. Resizing the window must trigger some event on the viewer that suddenly appears. I don't know how to fix this.  

About FX support, we have plans for a rewrite of the GUI, but sadly we don't have the manpower for it to happen any time soon.

**Comment by jordilaforge** [comment]
FX support would be really appreciated, lot of people are using FX now a days. Well the manpower is always an issue on open source projects..
So back to the SwingNode im sure the described behavior is a timing issue, if you manipulate the graph or just redraw the scene the graph appears. So I changed the code in my project and it works without NullPointer so far. 
Thank you for your efforts.
