### ISSUE TITLE
Workaround after removing ui.style

### ISSUE THREAD

**Issue by vibou** [graphstream/gs-core#212]
It is said in documentation that removing attribute ui.style does not actually remove the style that has been applied.

Is there any workaround to re apply CSS default style on the specific nodes?

**Comment by pigne** [comment]
I would suggest you the same suggestion that is made for regular CSS : avoid using ids. Prefer classes. You can't override ids. 

Define classes in the `ui.stylesheet`'s graph attribute, then add/remove classes  on the nodes with the `ui.class` attribute.

Example : 

```java 
graph.addAttribute("ui.stylesheet", ""+
   "node {"+
   "   fill-color:gray;"+
   "}"+
   "node.special {"+
   "   fill-color:red;"+
   "}");
// special node
aNode.setAttribute("ui.class", "special");
// ...
// not so special node. Will fall back to default style
aNode.removeAttribute("ui.class");  // or setAttribute("ui.class", "other classes");
```

Feel free to reopen if not clear.
