### ISSUE TITLE
singleton exception: id "..." already in use. / implement nodeClick listener

### ISSUE THREAD

**Issue by daald** [graphstream/gs-core#213]
I get the following exception:

> Exception in thread "main" org.graphstream.graph.IdAlreadyInUseException: singleton exception: id "A" already in use. Cannot create a node.
> 	at org.graphstream.graph.implementations.AbstractGraph.addNode(AbstractGraph.java:321)
> 	at org.graphstream.util.GraphListeners.nodeAdded(GraphListeners.java:412)
> 	at org.graphstream.graph.implementations.AbstractGraph.nodeAdded(AbstractGraph.java:733)
> 	at org.graphstream.stream.SourceBase.sendNodeAdded(SourceBase.java:323)
> 	at org.graphstream.ui.view.ViewerPipe.nodeAdded(ViewerPipe.java:301)
> 	at org.graphstream.stream.SourceBase.sendNodeAdded(SourceBase.java:323)
> 	at org.graphstream.stream.thread.ThreadProxyPipe.processMessage(ThreadProxyPipe.java:492)
> 	at org.graphstream.stream.thread.ThreadProxyPipe.pump(ThreadProxyPipe.java:270)
> 	at org.graphstream.ui.view.ViewerPipe.pump(ViewerPipe.java:97)
> 	at experiments.GraphTest.main(GraphTest.java:74)

The code:

```
package experiments;

import javax.swing.JFrame;
import javax.swing.WindowConstants;

import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.swingViewer.ViewPanel;
import org.graphstream.ui.view.Viewer;
import org.graphstream.ui.view.ViewerListener;
import org.graphstream.ui.view.ViewerPipe;

public class GraphTest {
	public static void main(String args[]) {
		Graph graph = new SingleGraph("Tutorial 1");
		graph.addNode("A");
		graph.addNode("B");
		graph.addNode("C");
		graph.addEdge("AB", "A", "B");

		JFrame frame = new JFrame();
		frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		frame.setVisible(true);
		frame.setSize(800, 600);
		Viewer viewer = new Viewer(graph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
		ViewPanel view = viewer.addDefaultView(false);
		frame.add(view);

		ViewerPipe fromViewer = viewer.newViewerPipe();

		fromViewer.addViewerListener(new ViewerListener() {
			@Override
			public void viewClosed(String arg0) {
				System.out.println("view closed " + arg0);
			}

			@Override
			public void buttonReleased(String arg0) {
				System.out.println("Button released on node " + arg0);
			}

			@Override
			public void buttonPushed(String arg0) {
				System.out.println("Button pushed on node " + arg0);
			}
		});
		fromViewer.addSink(graph);

		fromViewer.pump();
		int i = 0;
		while (true) {
			fromViewer.pump();  // <- this call throws the exception after ~ 9000 iterations
			System.out.println("Pumping....." + i++);
		}
	}
}
```

I don't see how this happens. Is the graph fed twice to the UI?

My goal is to simply catch `nodeClick` and `edgeClick` events. I'm surprised that this is so much more complex than `JButton.addActionListener()` or similar...

Used libs: gs-core-1.3.jar, gs-algo-1.3.jar

**Comment by pigne** [comment]
Just create the `Viewer` instance  *before* you start to modify the graph. This will prevent `Viewer` from trying the "replay" the graph, hence regenerating duplicated events. 

```java
Graph graph = new SingleGraph("Tutorial 1");
Viewer viewer = new Viewer(graph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
graph.addNode("A");
// ...
```
