### ISSUE TITLE
Bug fond in Camera.findNodeOrSpriteAt()

### ISSUE THREAD

**Issue by cezannealves** [graphstream/gs-core#217]
**When trying to use sprites to draw radiuses around nodes like this:**
![radius](https://cloud.githubusercontent.com/assets/21207850/22725560/5b66ba66-edb5-11e6-89ee-e33e7b0e1413.PNG)

**I couldn't click or move the nodes anymore, unless they were outside any sprites.
I thought initially that it could be due to the z coordinate or the z-index, but that was note tha case.**

**I turns out that findNodeOrSpriteAt () is implemented differently (from the simple viewer / camera and from documentation) in org.graphstream.ui.j2dviewer.camera.**

**View.findNodeOrSpriteAt doc says:**

"
Search for the first node or sprite (in that order) that contains the point at coordinates (x, y)
"

**ui.swingViewer.util.DefaultCamera.findNodeOrSpriteAt () does:**

"
for (Node n: graph) {
            GraphicNode node = (GraphicNode) n;
            if (nodeContains (node, x, y))
                return node;
        }
        for (GraphicSprite sprite: graph.spriteSet ()) {
            if (spriteContains (sprite, x, y))
                return sprite;
        }
        return null;
"

**But ui.j2dviewer.camera.findNodeOrSpriteAt () does:**

"
var ge: GraphicElement = null
  
  graph.getEachNode.foreach {n =>
  val node = n.asInstanceOf [GraphicNode]

  if (nodeContains (node, x, y))
  ge = node
  }

  graph.spriteSet.foreach {sprite =>
  if (spriteContains (sprite, x, y))
  ge = sprite
  }
  
 ge
"

**It overwrites ge every time it encounters a new element in the position, reversing the suposed priority of nodes over sprites.**

**I was using the release 1.3 from http://graphstream-project.org/download/ but i checked the source repository and its still that way in branch master and 2.x**

**I did not confirm this by changing and compling the code, but I think this is the problem.**

**In my opinion, the behavior of the simple viewer and documentation is more desirable than the last, but it would be nicer if it checked for the z-index, so it would pick what Were showing above and would give more control to the user.**

**Comment by pigne** [comment]
Yes, I spot that bug in the Scala version too. I also tend to agree with you about the z-index feature. That you give grater control over the click/select events. In the mean time I'll stick to fixing the bug.

**Comment by pigne** [comment]
Should be fixed by https://github.com/graphstream/gs-ui/commit/6e92e9fc4ade5bc2f449f568e819f79bf5200eac.

**Comment by pigne** [comment]
I'm closing this. Feel free to reopen if you still have the problem.

**Comment by cezannealves** [comment]
Thank you!
