### ISSUE TITLE
ConnectedComponents get subgraph nodes ???

### ISSUE THREAD

**Issue by cmdares** [graphstream/gs-core#218]
import java.util.Iterator;

import org.graphstream.algorithm.ConnectedComponents;
import org.graphstream.algorithm.ConnectedComponents.ConnectedComponent;
import org.graphstream.graph.Edge;
import org.graphstream.graph.Graph;
import org.graphstream.graph.Node;
import org.graphstream.graph.implementations.DefaultGraph;

public class CCTest {
	public static void main(String[] args) {
		Graph graph = new DefaultGraph("CC Test");
		//group 1
		graph.addNode("A");
		graph.addNode("B");
		graph.addNode("C");
		graph.addEdge("AB", "A", "B");
		graph.addEdge("AC", "A", "C");
		graph.addEdge("BC", "B", "C");
		//group 2
		graph.addNode("D");
		graph.addNode("E");
		graph.addNode("F");
		graph.addEdge("DE", "D", "E");
		graph.addEdge("DF", "D", "F");
		//separate the graph to sub connected components.
		ConnectedComponents cc = new ConnectedComponents();
		cc.init(graph);
		cc.compute();
		Iterator<ConnectedComponent> it = cc.iterator();
		while(it.hasNext()){
			System.out.println("--------group---------ok---------");
			ConnectedComponent ccx =it.next();
			System.out.println("sub_graph_id"+ccx.id);
			Iterator<Node> nodeiterator = ccx.iterator();
			while(nodeiterator.hasNext()){
				System.out.println("sub_graph_Node: why nodes is null ???");
				Node node =nodeiterator.next();
				System.out.println("node:"+node);
			}
		}
	}
}

**Comment by pigne** [comment]
```java
import java.util.Arrays;

public class NoRobot {
    public static void main(String[] args) {
        String answer[] = {"Greetings,", "\n", "Me", "no", "f...ing", "robot!!!", "\n", "Regards.", "\n"};
        Arrays.stream(answer).forEach(word -> System.out.printf("%s ",word));
    }
}
```
