### ISSUE TITLE
gs-ui not found

### ISSUE THREAD

**Issue by yangyi0318** [graphstream/gs-core#220]
gs-ui api not available. https://data.graphstream-project.org/api/gs-ui/current/

**Comment by pigne** [comment]
https://data.graphstream-project.org/api/gs-ui

Where did you get that URL from?

**Comment by yangyi0318** [comment]
From here http://graphstream-project.org/doc/API/

**Comment by pigne** [comment]
Thank you. Should be fixed now : http://graphstream-project.org/doc/API/
