### ISSUE TITLE
How to change line?

### ISSUE THREAD

**Issue by chienjchienj** [graphstream/gs-core#221]
How can i change line on node label?

I have tried following but it doesn't work

- \n
- \r\n  
- \newline
- \\

thanks!

**Comment by jordilaforge** [comment]
I haven't found a way to add a new line to a label. But what you can do is add a sprite and give it a label. That way you can add a text under your first label.

**Comment by pigne** [comment]
Sorry. Not possible yet. Your best option for now is the one @jordilaforge gave.
