### ISSUE TITLE
Using sun intern librarys

### ISSUE THREAD

**Issue by MaSven** [graphstream/gs-core#223]
We should avoid using the sun librarys. In the upcoming release of java this will run into troubles.

[HTTPSource](https://github.com/graphstream/gs-core/blob/master/src/org/graphstream/stream/net/HTTPSource.java)

Maybe we should look if we can use a different library or how other projects done it. 

[Elasticsearch](https://github.com/policeman-tools/forbidden-apis/issues/103) ran into the same problem and solved it.

**Comment by gsavin** [comment]
Sounds like a good idea.
I will try to do it for the future 2.0.

Thanks.

**Comment by MaSven** [comment]
No problem maybe i will look into it. But it will take one week i guess till i have time for it.
