### ISSUE TITLE
Viewer setCloseFramePolicy, CLOSE_VIEWER seems not working

### ISSUE THREAD

**Issue by charles1017** [graphstream/gs-core#229]
I am on macOS 10.12.3 with eclipse, JDK1.7, gs-core-1.3 from official website.

Part of my code is like this.

Viewer viewer = new Viewer(graph, Viewer.ThreadingModel.GRAPH_IN_GUI_THREAD);
viewer.setCloseFramePolicy(Viewer.CloseFramePolicy.CLOSE_VIEWER);
viewer.enableAutoLayout();
viewer.addDefaultView(true);

When I click the close button ("x"), the program is still running, but the frame is gone.

Is the a known bug? or its my problem?

Please let me know if you need more information from me.
Thanks!

**Comment by pigne** [comment]
That's precisely what the `CLOSE_VIEWER` policy is meant to do : closing the viewer but not exiting the application.

If you want the program to quit as soon as you click the "x" button, then use the `EXIT` policy.

**Comment by charles1017** [comment]
My program has a main Frame, after I click a button, the frame using graphstream will pop up.

If I use EXIT, my main frame (the whole application) will close as well.
