### ISSUE TITLE
How to turn around (align) the graph?

### ISSUE THREAD

**Issue by ultimate2106** [graphstream/gs-core#238]
So our Graph is mirrored horizontal to our actual gamemap when we use the x and y attributes in the nodes to get a grid. How to turn the graph around to match the actual gamegrid?

**Comment by pigne** [comment]
Sounds like you only need to get an opposite value for y. 
If you need absolute values, you need the max value of y, and do something like y = maxY - y 
If you just need relative positioning, just do some sort of y = -y
`n.setAttribute("y", -1.0 * n.getNumber("y")); `
