### ISSUE TITLE
Topological Sorting does not run in linear time for some graphs

### ISSUE THREAD

**Issue by MayanHut** [graphstream/gs-core#241]
Although the algorithmic complexity of the DFS topological sorting algorithm is O(V + E) (where V is the number of vertices and E the number of edges in the graph), the provided implementation has worst case complexity O(V^2) even when E is 0.

Consider a graph with V vertices and no edges. Then in the code below only one vertex gets marked in each call of `visitNode(..).` However, the loop in `getUnmarkedNode(..)` gets restarted every time. So it executes 1 + 2 + 3 + ... + V = O(V^2) times in total. 

```java
    private void computeDFS() {
        ...
        while ((n = getUnmarkedNode(marks)) != null) {
            visitNode(n, marks);
        }
    }

    private Node getUnmarkedNode(int[] marks) {
        for (int i = 0; i < marks.length; i++) {
            if (marks[i] == MARK_UNMARKED) {
                return graph.getNode(i);
            }
        }
        return null;
    }
```

To fix this, just make the iterator a private variable and reset it only when calling `computeDFS()`. This guarantees that the body of the loop will execute amortised linear (in V) times.

**Comment by jordilaforge** [comment]
hi mayanhut

If we are talking about worst case complexity you are right. Thank you for pointing that out but I do not quite understand your fix. Can you provide a Pull Request with the fix?
