### ISSUE TITLE
Java9

### ISSUE THREAD

**Issue by MaSven** [graphstream/gs-core#243]
With the upcoming of java 9, is there any plan when graphstream will be ready for it? Im sure first maven and alle dependencys have to be java9 compatible but will graphstream work with Java 9 JRE? Maybe this sould be a milestone? 

I think the project has to be restructured to be compatible. I tried it today and failed with the maven dependencys. Maybe someone else got it work?.

**Comment by jordilaforge** [comment]
Hi MaSven

I do not see why graphstream should not be working with Java9 after all Java9 just introduces some new features. Do you get compiler errors?

**Comment by MaSven** [comment]
Yes quite a lot i have a log here from maven. 
[maven_install.txt](https://github.com/graphstream/gs-core/files/1259841/maven_install.txt)
It is the new Module system that breaks our code. I think we have to define an module-info.java file for this. Also the project structure must be different.

**Comment by MaSven** [comment]
Also when targeting jdk 1.8 in java9 enviremont i get other error related to maven i think.
[maven_install_jdk8.txt](https://github.com/graphstream/gs-core/files/1259889/maven_install_jdk8.txt)
maybe an update of the maven plugins will to the trick to compile to java 8?

**Comment by pigne** [comment]
Which branch do you test your compilations against? 

The `master` branch still matches branch 1.X (1.3 actually) of gs-core which was not tested with java8 or 9. 

The `2.x` branch is java8  compatible.

**Comment by MaSven** [comment]
tested with the 2.x branch. I now git it compiled only had to get some version numbers right in the pom.

**Comment by MaSven** [comment]
I will close this as it compiles now with java9. But to target Java9 there need to be done more.
