### ISSUE TITLE
id  already in use. Cannot create a node

### ISSUE THREAD

**Issue by morellik** [graphstream/gs-core#246]
I'm trying to use graphstream but I encounter a problem with id. I've to create a graph with a vertex and a lot of nodes. All arrows has to start from the vertex to each node. [Example](http://www.cerm.unifi.it/static/757_1.png) When I use addEdge I receive the error reported in the title. Is there a way to do that?

**Comment by MaSven** [comment]
I think you have to disable strict checking for this in your graph. Also dont give every node not the same ID

**Comment by gsavin** [comment]
Not sure of what difference you are doing between vertices and nodes but anyway, your error means you are trying to create a node that already exists. If it's during addEdge it's a bit weird. Can you add some code to reproduce ?

**Comment by morellik** [comment]
The first should create a vertex node from where all arrows should start.

     List<String> nBorList = new ArrayList<>();
        for (InteractionHbond ib : interactions) {
            for (Atom at : ib.getAtoms()) {

                String[] neigRes = at.getNeigh_atom_str().split(" ");
                String node = null;
                String node1 = null;
                if(first) {
                    String[] ligRes = at.getLig_atom_str().split(" ");
                    node = ligRes[0]+"_"+ligRes[1];
                    graph.addNode(node);
                    first = Boolean.FALSE;
                }

                if(!nBorList.contains(neigRes[0]+"_"+neigRes[1])) {
                    nBorList.add(neigRes[0]+"_"+neigRes[1]);
                    node1 = neigRes[0]+"_"+neigRes[1];
                    graph.addNode(node);
                    String id = graph.getId();
                    graph.addEdge(node, node, node1);

                    y +=50;
                }
            }
        }

**Comment by gsavin** [comment]
I guess there are some parts of your code missing.
You are trying to add several time the node `node`, and you are always using the same id for the edge.

For what I understand of what you are trying to do, it would more look like this :

```java
List<String> nBorList = new ArrayList<>();
String node = null;
for (InteractionHbond ib : interactions) {
  for (Atom at : ib.getAtoms()) {
    String[] neigRes = at.getNeigh_atom_str().split(" ");
    String node1 = null;
    if(node == null) {
      String[] ligRes = at.getLig_atom_str().split(" ");
      node = ligRes[0]+"_"+ligRes[1];
      graph.addNode(node);
    }

    if(!nBorList.contains(neigRes[0]+"_"+neigRes[1])) {
      nBorList.add(neigRes[0]+"_"+neigRes[1]);
      node1 = neigRes[0]+"_"+neigRes[1];
      graph.addNode(node1);
      String id = graph.getId();
      graph.addEdge(node + "--" + node1, node, node1);

      y +=50;
    }
  }
}
```

**Comment by morellik** [comment]
Thanks, I tried, the error is disappeared but the graph has only one black circle in the middle.

**Comment by gsavin** [comment]
It's certainly mean that you do not enable the autolayout. If not enable you have to specify positions by yourself. Else nodes will all have the same position which will result in a single circle in the middle.
