### ISSUE TITLE
How to detect mouse click on a node

### ISSUE THREAD

**Issue by githublemming** [graphstream/gs-core#251]
Hi,

I can't seem to find any documentation on how to detect a click event on a node. What I want to do is click on a node and then display some information. Is there a way of doing this?

Thanks,

Mark

**Comment by pigne** [comment]
Yes. 
- retrieve click events : 
http://graphstream-project.org/doc/Tutorials/Graph-Visualisation/#retrieving-mouse-clicks-on-the-viewer
- display extra information on the viewer (with sprites): 
http://graphstream-project.org/doc/Tutorials/Graph-Visualisation/#adding-some-symbols
