### ISSUE TITLE
Sample app?

### ISSUE THREAD

**Issue by CaptainZippy** [graphstream/gs-core#259]
Background - The DGS streaming format looks like pretty much perfect fit for my application.
I can produce a DGS stream from a non-java application and see visualize progress.
But having to start writing java code is a pretty major obstacle to even trying GS.
A sample app which could read from a file or socket (with an option to poll when eof reached) would go a long way to getting started.

**Comment by sbalev** [comment]
Hi,

I think this one is a good starting point:
http://graphstream-project.org/doc/Tutorials/Reading-files-using-FileSource/

**Comment by CaptainZippy** [comment]
Thanks for the quick reply but this request is more about an executable app with graphstream in it.
Ideally it would not require installation of a JDK (JRE would be OK of course) or any coding.

Seeing as there's so much functionality in the gs libs, it seems a shame that
java -jar gs-ui.jar doesn't do anything useful.
