### ISSUE TITLE
Random automatic layout

### ISSUE THREAD

**Issue by jansvajcr** [graphstream/gs-core#263]
Each visualisation of a **single** model/graph gives totally different layout when using automatic layout (_Viewer.enableAutoLayout()_). Is it somehow possible to achieve the same layout using the automatic layout feature?

**Comment by pigne** [comment]
Interesting question. You can control the random number generator used by the layout algorithm. So I guess this can help you achieve the same layout. 

Here is how you would do it (path may vary depending on your version): 

```java
import org.graphstream.ui.layout.springbox.implementations.SpringBox;
// ...
Random  myRandom = new Random(1234);
// ...
viewer.enableAutoLayout( new SpringBox(false/*no 3d*/, myRandom));
```

**Comment by jansvajcr** [comment]
It works. Thank you!
