### ISSUE TITLE
HTTPSource requires too many dependencies 

### ISSUE THREAD

**Issue by pigne** [graphstream/gs-core#269]
The new version (2.x branch) of `HTTPSource` depends on many external libraries  (`Spark`, `apache.commons`, `apache.httpcomponent`) that add up to the payload of the gs-core jar file when building a dependency-included archive. 

The archive with those deps is around 3.4 MB while it stays below 1MB without those deps. 

Should we pull `HTTPSource` from gs-core and put it in its own project (`gs-httpsource`) ? 

cc: @MaSven 
cc: @gsavin

**Comment by MaSven** [comment]
I think this would be a good idea.

**Comment by MaSven** [comment]
Should this be an optional dependency on gs-core or rather an own maven project?

**Comment by gsavin** [comment]
Definitely `gs-core` should be as light as possible.
Another solution would be to keep it in `gs-core` without including its deps into the final package but sounds less clean than having its own `gs-httpsource` project (maybe `gs-source-http` to have a common `gs-source-` prefix for this kind of sources).

**Comment by MaSven** [comment]
i made a test project. It was rather fast to outsource httpsource from the rest of the code. 
[gs-httpsource](https://github.com/MaSven/gs-httpsource)

**Comment by pigne** [comment]
Ok, Thanks guys for your comments. I propose to fork @MaSven's `gs-httpsource` project into the graphstream org, then rename it to `gs-source-http` according to @gsavin's proposal.

OK to tag `gs-core` as "provided" in the deps. 

No there is not any parent pom in the graphstream org. Should we have one?

**Comment by pigne** [comment]
For the record: 
- new project here: [gs-source-http](https://github.com/graphstream/gs-source-http)
- HTTPSource removed from gs-core there: https://github.com/graphstream/gs-core/commit/49d788fcc7875cf4226f5f3d899a14922f13231b

**Comment by MaSven** [comment]
Maybe a parent pom makes sense. So that every child project has the same license as default. Some dependencies are the same such as junit. The contributors are the same i guess. I think this could also help on the CI/CD site. Also some of the properties are held on one place and doesn't have to change in many projects. As example the java version.
