### ISSUE TITLE
FileSinkImages's renderers

### ISSUE THREAD

**Issue by pigne** [graphstream/gs-core#271]
`FileSinkImages` uses the old renders as well as constants to refer to them : 

https://github.com/graphstream/gs-core/blob/f9826fd4c0a756b73f974b66c833c05ef4d421a7/src/org/graphstream/stream/file/FileSinkImages.java#L240-L247

2 points to be addressed: 

1) Since there is no more renderer in `gs-core`, I guess the all `RendererType` is getting obsolete. Or at least need to be rethink. 
2) Will FileSinkImage work with new renderers?

**Comment by gsavin** [comment]
`FileSinkImages` creates a `Graphics2D` from a `BufferedImage` and then feeds the old renderer with this graphics object, If the new renderer does not work wit `Graphics2D`, we will have to define another way.

**Comment by gsavin** [comment]
If used with the JavaFX renderer, we will need to use `WritableImage` instead of `BufferedImage` and to access the `snapshot()` method of the canvas somewhere somehow...

**Comment by hichbra** [comment]
Since it's a class dependent mainly of the technology used, we can keep a common base in gs-core (superclass or interface ?) and implements problematics methods in UIs.
