### ISSUE TITLE
Not able to parse css file

### ISSUE THREAD

**Issue by galactro50** [graphstream/gs-core#275]
Error:

WARNING: Error while parsing style sheet for graph 'GraphicGraph_3863'.
java.io.IOException: Encountered " <IDENTIFIER> "myStyle "" at line 1, column 1.
Was expecting one of:
    <EOF> 
    "graph" ...
    "edge" ...
    "node" ...
    "sprite" ...
    <COMMENT> ...

Css file:

node {
	size: 3px;
	fill-color: #777;
	text-mode: hidden;
	z-index: 0;
}

edge {
	shape: line;
	fill-color: #222;
	arrow-size: 3px, 2px;
}

**Comment by hichbra** [comment]
Hi ! Can you share your code ?

**Comment by galactro50** [comment]
package graphstream_1;

//import anything I might need
import org.graphstream.graph.*;
import org.graphstream.graph.implementations.*;
import org.graphstream.stream.file.*;
import org.graphstream.algorithm.*;
import org.graphstream.ui.layout.*;
import java.io.IOException;
@SuppressWarnings("unused")

public class pleaseHelpMe {
    public static void main(String args[]) throws IOException, InterruptedException {
        //do something that was in some code somewhere...
        //please explain
        System.setProperty("org.graphstream.ui.renderer","org.graphstream.ui.j2dviewer.J2DGraphRenderer");

        //instantiate a graph
        Graph graph = new SingleGraph("thisGraphNeedsHelp");

        graph.addNode("A" );
        graph.addNode("B" );
        graph.addNode("C" );
        graph.addEdge("AB", "A", "B");
        graph.addEdge("BC", "B", "C");
        graph.addEdge("CA", "C", "A");

        graph.addAttribute("ui.antialias"); //this does something...
        graph.addAttribute("ui.quality"); //this sounds less important...
        graph.setAttribute("ui.stylesheet", "myStyle"); //get some style
        graph.display();//this just makes the canvas?

    }
}

**Comment by gsavin** [comment]
Assuming `myStyle.css` is your CSS file you should use `graph.addAttribute("ui.stylesheet", "url(myStyle.css)");`.

**Comment by hichbra** [comment]
Here :
graph.setAttribute("ui.stylesheet", "myStyle"); //get some style
you put a string instead of your variable

**Comment by galactro50** [comment]
Hi gsavin,

After using your suggestion, I am getting the following error:

```
Feb 26, 2018 6:35:08 PM org.graphstream.ui.graphicGraph.GraphicGraph attributeChanged
WARNING: Error while parsing style sheet for graph 'GraphicGraph_5806'.
java.net.MalformedURLException: no protocol: myStyle.css
```

**Comment by galactro50** [comment]
Hey hichbra,

I didn't getting which variable you are talking about.
myStyle.css is my css file name which is in the same folder as the main file.

**Comment by galactro50** [comment]
Using variable also giving me the same error
```
Feb 26, 2018 6:59:19 PM org.graphstream.ui.graphicGraph.GraphicGraph attributeChanged
WARNING: Error while parsing style sheet for graph 'GraphicGraph_3553'.
java.io.IOException: Encountered " <IDENTIFIER> "myStyle "" at line 1, column 1.
Was expecting one of:
    <EOF> 
    "graph" ...
    "edge" ...
    "node" ...
    "sprite" ...
    <COMMENT> ...
```

**Comment by gsavin** [comment]
@galactro50 when loading from an URL, the stylesheet first try to check if the file exists before creating a URL object. The `MalformedURLException` you are getting means your file can not be found, and the URL is failing because there is no protocol specified on it.

Where is you css file located ? If specified like this, it should be at the root of your working directory.

**Comment by hichbra** [comment]
If you want to use a css file, please check the link to this file.
`java.net.MalformedURLException: no protocol: myStyle.css`
You get this error because the file myStyle.css is not found.
```java
// If you try this
File f = new File("myStyle.css");
System.out.println(f.exists()); // This will probably print false
```
And the other solution is to put a style parameter directly in your code : 
```java
String myStyle = "node {"
    			+ "size: 3px;"
    			+ "fill-color: #777;"
    			+ "text-mode: hidden;"
    			+ "z-index: 0;"
    			+ "}"

    			+ "edge {"
    			+ "shape: line;"
    			+ "fill-color: #222;"
    			+ "arrow-size: 3px, 2px;"
    			+ "}";
        
graph.setAttribute("ui.stylesheet", myStyle);
```
Good luck

**Comment by gsavin** [comment]
@galactro50 What @hichbra means is that you can specify the content of your file inside a String variable (rather than using an external file):

```java
String myStyle = "node { fill-color: red; }";
graph.setAttribute("ui.stylesheet", myStyle);
```

**Comment by galactro50** [comment]
Thank you @hichbra @gsavin 
With variable, it worked.
Thank you so much
