### ISSUE TITLE
Overlapping edges and nodes

### ISSUE THREAD

**Issue by galactro50** [graphstream/gs-core#276]
I have to implement a feature for which I need the graph visualisation. I have used graphstream for the same.
`Notes: Number of nodes to be displayed are dynamic and the information is parsed from a file in the run-time.`

I have implement the algorithm but the problem is nodes and labels are overlapping.
Manually assigning coordinates may not be an option which is feasible in the dynamic case.

I am pasting a screenshot and removed the labels for the privacy purpose. 
Please help me out.

<img width="1680" alt="screen shot 2018-03-02 at 12 29 48 pm" src="https://user-images.githubusercontent.com/11232510/36887198-101cd68e-1e16-11e8-841a-858219cf62c7.png">

**Comment by hichbra** [comment]
Hi ! Do you use the default layout algorithm of GraphStream ?

**Comment by galactro50** [comment]
@hichbra What I used was something like below:

```
        System.setProperty("org.graphstream.ui.renderer","org.graphstream.ui.j2dviewer.J2DGraphRenderer");
        Graph graph = new MultiGraph("Tutorial 1");
/* Then my algorithm */

       Viewer viewer = graph.display();
        // Let the layout work ...
        //viewer.enableXYZfeedback(true);
        viewer.enableAutoLayout();
```

Please let me know the better ways to display. And the ways to increase repulsion between the nodes, edges .

style file

```
graph {
	fill-color:yellow; /*rgb(225,225,225); */
	/* A bit of gray!*/
}
edge {
	size:5px;
	arrow-size:10;
	fill-color: rgb(127,0,55);
}

node.red{
	size:150px;
    fill-color: red;
    text-size:20px;

}

node{

	size:100px;
	fill-color: green;
	text-size:20px;
	}
```

**Comment by hichbra** [comment]
you can use attributes for custom the layout algorithm comportement. See here :
http://graphstream-project.org/doc/FAQ/Attributes/Is-there-a-list-of-attributes-with-a-predefined-meaning-for-the-layout-algorithms/
