### ISSUE TITLE
package org.graphstream.ui.view.camera in core?

### ISSUE THREAD

**Issue by raminsadre** [graphstream/gs-core#277]
Hi,

I wanted to compile ui-swing and ui-javafx but they need the package org.graphstream.ui.view.camera.
I can't find it. Should it be part of core?

Btw, do I understand correctly that ui-swing and ui-javafx will replace the old full scala-renderer?

Best

**Comment by hichbra** [comment]
That is correct, gs-ui-(...) will replace the old scala renderer in the version 2.
For compile them, you need to use the branch 2.x in gs-core.

**Comment by raminsadre** [comment]
Thanks. I have just ported my application to version 2 with ui-javafx. Looks cleaner now. Good work!
