### ISSUE TITLE
customizing the rendering process

### ISSUE THREAD

**Issue by raminsadre** [graphstream/gs-core#278]
Hi,
My main concern with graphstream at the moment is how difficult it is to customize the rendering process  (without writing a new GraphRenderer). Just an example: I don't like how multi-edges are drawn in the full renderer.  In mxGraph, I would simply define a new edge shape. I have not yet found an obvious way how to do that in graphstream. Although the code is nicely organized in classes, most (all?) of the workflow is hardcoded and I don't see an obvious way to tell the system to use my own implementation for a particular aspect of the rendering.
Are there plans to address this problem in the new version?

**Comment by hichbra** [comment]
For the moment, I recommend to search in the CSS properties a solution would suit you best.

Indeed, you can't replace one specific shape for your own without redefine the library or create a new renderer. A renderer is a point of view about "how a graph should be drew", this is why there can be more than one in the same project. We are not plan to change that in the version 2.

If you don't want to redefine a new renderer, you can search in the library the class where the shape is drawing. All shapes is defined in org.graphstream.ui.javafx.renderer.shape.javafx...
For your exemple, you need to redefine the class LineShape in package baseShapes.

But it's a relevant idea and we save it for a future version, thank you.
