### ISSUE TITLE
Multiple Nodes with same Labels

### ISSUE THREAD

**Issue by TheFrozenDuck** [graphstream/gs-core#282]
I'm currently working on a project which requires us to display a directed graph. To improve the readability (so edges don't cross, etc.) for the users we'd like to have a certain set of nodes which appears multipe times like this:

X ------ Y 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Z ------ A
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/
X --------------- B

As `addNode()` in Graph doesn't support this I was wondering if there is a simple workaround for this, or if this is a hopeless task.

Kind regards, and thanks in advance.

**Comment by hichbra** [comment]
`addNode()` takes the unique string identifying the node, but you can define a label with 
`setAttribute( "ui.label", ...)`

**Comment by TheFrozenDuck** [comment]
I guess I couldn't see the forest for the trees. I'm going to close this issue now.
