### ISSUE TITLE
Roatating the Graph

### ISSUE THREAD

**Issue by TheFrozenDuck** [graphstream/gs-core#285]
Hi there,
I've been wondering if there's a way to rotate the graph, so that the HierarchicalLayout p.e., displays the graph from left to right, instead of top to down. One could rotate the whole pane with JavaFX, but it would rotate also the labels of the graph, and this is unfortunate for me.

Thanks in davance.

**Comment by TheFrozenDuck** [comment]
Thank you for the answer. I tested it, but the problem is the user would have to hold the combination for quite a while. I tried to look for the method called to rotate and found "autoFitView" but I'm not sure if that is the right one. I really would like to just call the method, any hints would be appreciated.

**Comment by ThibautDemare** [comment]
I don't use the HierarchicalLayout, so maybe I am wrong and I don't understand your problem, but when I read your comments, I think that you could update the coordinates of your nodes and apply them a rotation like this :
```
double x = node.getNumber("x");
node.setAttribute("x", -1*node.getNumber("y"));
node.setAttribute("y", x);
```
And you apply this code to every node of your graph.

**Comment by hichbra** [comment]
If you want to change the rotation programmatically, you can use the method `setViewRotation` of Camera.
