### ISSUE TITLE
GraphStream：How to achieve Zoom and Pan

### ISSUE THREAD

**Issue by anny130688** [graphstream/gs-core#290]

**Comment by hichbra** [comment]
http://graphstream-project.org/doc/Tutorials/Graph-Visualisation/

**Comment by hichbra** [comment]
https://github.com/graphstream/gs-core/issues/289

**Comment by anny130688** [comment]
I am trying to do this demo drawing GIS data http://graphstream-project.org/doc/Tutorials/Graph-Visualisation/.In Le Havre.dgs ,The coordinates of the point are geographic coordinates.But in the panning operation, the coordinates obtained are the coordinates on the screen.

**Comment by hichbra** [comment]
Do you have include gs-algo package ?

**Comment by anny130688** [comment]
I have find the tool toolkit.But I can't achieve Pan.

**Comment by hichbra** [comment]
which version of core/algo and ui are you using ?

**Comment by anny130688** [comment]
1.3

**Comment by hichbra** [comment]
I can't reproduce the error, try `GraphPosLengthUtils.nodePosition` instead of `Toolkit.nodePosition`

**Comment by anny130688** [comment]
This has been solved.The problem now is that when panning, the mouse changes a bit and the graph will shift a lot. The coordinate values will also increase or decrease.

**Comment by anny130688** [comment]
The problem Toolkit is resolved.But,I have another question.When panning, the mouse changes a bit and the graph will shift a lot. The coordinate values will also increase or decrease ,even disappear in the view.
