### ISSUE TITLE
How to get the coordinates of a node on the screen without setting the actual coordinates of the point

### ISSUE THREAD

**Issue by anny130688** [graphstream/gs-core#292]
No node coordinates are assigned when the node is initialized. How to get the coordinates of the node displayed on the screen

**Comment by hichbra** [comment]
`Toolkit.nodePosition(node)` gives you the relative position of a node, don't forget to allow time for the viewer.

```java
Viewer v = graph.display();
DefaultView view = (DefaultView) v.getDefaultView();

try {	// Allow time for the viewer to build
	Thread.sleep(500);
} catch (InterruptedException e) {
	e.printStackTrace();
}
		
graph.nodes().forEach(n -> { // Only in GraphStream 2.0, otherwise use the traditional loop in lower versions
	double[] relative = Toolkit.nodePosition(n);
	System.out.println("Relative = "+relative[0]+" "+relative[1]);
	
	Point3 position = view.getCamera().transformGuToPx(Toolkit.nodePosition(n)[0], Toolkit.nodePosition(n)[1], 0);
	System.out.println("Coordinate = "+position);
});
```

**Comment by TobiasIsak** [comment]
Can't seem to find this "toolkit" in the gs-core or gs-ui-android, is there anything specific that needs to be done on android to be able to get the location of a node?

**Comment by hichbra** [comment]
[Toolkit](https://github.com/graphstream/gs-algo/blob/2.0-alpha/src/org/graphstream/algorithm/Toolkit.java) is in gs-algo library. You can use Toolkit in onStart(), and if it's done in a thread don't forget to allow time with sleep() at the start of the thread.
