### ISSUE TITLE
tiny copy-paste mistake in ViewerPipe

### ISSUE THREAD

**Issue by ku-antum** [graphstream/gs-core#306]
Thanks for this great software!

There seems to be a tiny copy-paste mistake in ViewerPipe;
see the following diff (function in ViewerPipe:257-270, line 266):
```
public void nodeAttributeRemoved(String sourceId, long timeId,
			String nodeId, String attribute) {
		sendNodeAttributeRemoved(sourceId, timeId, nodeId, attribute);

		if (attribute.equals("ui.clicked")) {
			for (ViewerListener listener : viewerListeners)
				listener.buttonReleased(nodeId);
		}

-		if (attribute.equals("ui.mouseOver")) {
+		if (attribute.equals("ui.mouseLeft")) {
			for(ViewerListener listener: viewerListeners)
				listener.mouseLeft(nodeId);
		}
}
```

Are these events actually ever triggered (in latest snapshot)?
I only received button push& release.

**Comment by hichbra** [comment]
It's not a copy-paste mistake, mouseOver and mouseLeft are not implemented yet by default in the UI projects (gs-ui-swing, gs-ui-javafx and gs-ui-android), this is why these events are not triggered. The generic attributes (ui.mouseOver and ui.mouseLeft) are here for these functions.

You can use these functions with Swing if you add : 
```java
viewer.getDefaultView().setMouseManager(new MouseOverMouseManager(10));
```
If you are interested, you can look the relating classes : [DefaultMouseManager](https://github.com/graphstream/gs-ui-swing/blob/2.0-alpha/src/org/graphstream/ui/swing_viewer/util/DefaultMouseManager.java)`and [MouseOverMouseManager](https://github.com/graphstream/gs-ui-swing/blob/2.0-alpha/src/org/graphstream/ui/swing_viewer/util/MouseOverMouseManager.java) for gs-ui-swing, [FxMouseManager](https://github.com/graphstream/gs-ui-javafx/blob/master/src/org/graphstream/ui/fx_viewer/util/FxMouseManager.java) for gs-ui-javafx and [DefaultMouseManager](https://github.com/graphstream/gs-ui-android/blob/master/app/src/main/java/org/graphstream/ui/android_viewer/util/DefaultMouseManager.java) for gs-ui-android.

**Comment by ku-antum** [comment]
Thanks!
Two questions:
1) Still, after enabling the above events the current code of ViewerPipe would never report a mouseLeft event to listeners (because the if  condition checks for mouseOver)?
2) Which git tag/branch across the various gs-* repos could/should be used for current development? 
(I'm intending to build all gs-* components from scratch and there are different git tag/branches.)

**Comment by ku-antum** [comment]
Thanks!

Still, after enabling the above events no mouse left event would be reported to listeners in the current code of ViewPipe (because the if condition checks for ui.mouseOver).

**Comment by hichbra** [comment]
```java
public void nodeAttributeRemoved(String sourceId, long timeId, String nodeId, String attribute) {
	sendNodeAttributeRemoved(sourceId, timeId, nodeId, attribute);
	
	if (attribute.equals("ui.clicked")) {
		for (ViewerListener listener : viewerListeners)
			listener.buttonReleased(nodeId);
	}

	if (attribute.equals("ui.mouseOver")) {
		for (ViewerListener listener : viewerListeners)
			listener.mouseLeft(nodeId);
	}
}
```
1-  You are inside the nodeAttributeRemoved() function. When the "ui.mouseOver" attribute is removed, that mean the mouse left, so mouseLeft() is called. I do not see anything wrong with that.

2- The "dev" branch is the current development branch, 2.0-alpha tag is the last release.

**Comment by ku-antum** [comment]
add1) Ah, ok, of course you're right.  Thanks for the explanation!
add2) Thanks, I will use the dev branch then.  The gs-ui module doesn't have a dev branch.  Is `gs-ui-swing` the 'main' ui project now?

All questions were resolved successfully, closing now.
Many thanks!

**Comment by hichbra** [comment]
gs-ui-javafx ans gs-ui-swing are the main
