### ISSUE TITLE
Compilation error in 2.0 alpha

### ISSUE THREAD

**Issue by bempelise** [graphstream/gs-core#317]
I am trying to use Graphstream for a graph representation on a Swing GUI. I have been using `gs-core` and `gs-ui-swing` both at `2.0-alpha`. I am getting

```
error: cannot find symbol
 graph.addAttribute("ui.stylesheet", "node { text-size:8; text-color: #0008; text-alignment: at-right; } edge { text-size:8; text-color: #0008; }");
  symbol:   method addAttribute(String,String)
  location: variable graph of type SingleGraph

```
Where `graph` is a `org.graphstream.graph.implementations.SingleGraph` object.
I can see that the `addAtribute `is a variadic method in `AbstractElement` but it looks it is not found by javac(?) in my case...

Any ideas on this?
I am using `javac 1.8.0_131`

**Comment by hichbra** [comment]
addAtribute() method no longer exists in 2.0-alpha, use setAttribute()

**Comment by bempelise** [comment]
Thank you this did it. Is there any plan on updating the API and example with the 2.0 version soon?

**Comment by hichbra** [comment]
Yes, it's planned, but I don't know when yet.
