### ISSUE TITLE
Node label is not displayed in the center of the node

### ISSUE THREAD

**Issue by younes1758** [graphstream/gs-core#318]
I want to display the label of the nodes inside it, but the labels are always in the right of the nodes. My simple code is:

        Grapg graph = new SingleGraph("tuto");
        graph.setAttribute("ui.stylesheet", "url('stylesheet')");        
        graph.addNode("n1");
        graph.getNode("n1").setAttribute("xy", 10, 10);
        graph.getNode("n1").setAttribute("ui.label", "n1");
        graph.getNode("n1").setAttribute("ui.color", Color.yellow);

        graph.addNode("n2");
        graph.getNode("n2").setAttribute("xy", 40, 30);   
        graph.getNode("n2").setAttribute("ui.label", "n2");
        graph.getNode("n2").setAttribute("ui.color", Color.yellow);
        
        graph.addEdge("n12", "n1", "n2");

       graph.display();

And the file stylesheet has the following configuration:

	node{
		z-index: 1;
		text-mode: normal;	
		text-alignment: center;
		text-size: 10;		
		size: 40px;	
		fill-mode: dyn-plain;
	}

	edge {
		z-index: 0;
		arrow-shape: none;
		fill-mode: dyn-plain;	
	}

So after excuting this code all the labels are dipslayed in the right of the node, even if i change 
text-alignment in stylesheet to left, at-left, at-right, under or any position it will be always in the right, and i don't know why, any help please?

**Comment by hichbra** [comment]
It works for me. You can make your css in a string 
```java
String stylesheet = "node{z-index: 1; text-mode: normal; text-alignment: right; text-background-mode: plain; text-size: 10; size: 40px; fill-mode: dyn-plain; } edge {z-index: 0; arrow-shape: none; fill-mode: dyn-plain; }";
```
```java
graph.setAttribute("ui.stylesheet", stylesheet);
```
If it work then the issue is in your stylesheet url. If it doesn't, then look around your packages.

Also I don't know which UI you use, but don't forget your system property.
```java 
// This syntax only works with Graphstream 2.0-alpha
System.setProperty("org.graphstream.ui", "javafx"); // or swing
```
