### ISSUE TITLE
Maven import failed

### ISSUE THREAD

**Issue by thomakl** [graphstream/gs-core#319]
Hi,

When I try to install `gs-core` from maven as mentioned [here](http://graphstream-project.org/doc/Tutorials/GraphStream-Maven/) ; it says : ` Missing artifact org.graphstream:gs-core:jar:1.1`
I change the version to `2.2.0-SNAPSHOT`: same issue.

**Comment by hichbra** [comment]
Maven users, you may include gs-core as a dependency to your project using (https://jitpack.io). Simply add the jitpack repository to the pom.xml:
```xml
<repositories>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>
```
then, add the gs-core to your dependencies:
```xml
<dependency>
    <groupId>com.github.graphstream</groupId>
    <artifactId>gs-core</artifactId>
    <version>2.0-alpha</version>
</dependency>
```

**Comment by thomakl** [comment]
Thank you for your quick answer. I'll make a try
