### ISSUE TITLE
Removing an Edge - ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Runster** [graphstream/gs-core#322]
Hey!

The following code ends up in an Exception:

`		Graph graph = new SingleGraph("example");
		
		graph.addNode("a");
		graph.addNode("b");
		graph.addEdge("ab", "a", "b");
		
		Edge edge = graph.getEdge("ab");
		
		Graph tempGraph = Graphs.clone(graph);
		
		tempGraph.removeEdge(edge);
		graph.removeEdge(edge);`

Seems like he noticed in the original Graph, that the edge has been removed. My workaround for this problem is to remove the Id (String) of the edge, not the object itself.

**Comment by hichbra** [comment]
You need to use the Id of the edge, not the object itself.
```java
graph.addNode("a");
graph.addNode("b");
graph.addEdge("ab", "a", "b");
	
Edge edge = graph.getEdge("ab");

Graph tempGraph = Graphs.clone(graph);
	
tempGraph.removeEdge(edge.getId());
graph.removeEdge(edge.getId());`
```

**Comment by Croydon** [comment]
Isn't removal via edge object supposed to work?

https://data.graphstream-project.org/api/gs-core/current/org/graphstream/graph/implementations/AbstractGraph.html#removeEdge(org.graphstream.graph.Edge)

https://github.com/graphstream/gs-core/blob/807bea7bb818eaba28f47b0f33e565cd600a627a/src/org/graphstream/graph/implementations/AbstractGraph.java#L285

**Comment by hichbra** [comment]
Yes of course, but in this case the wrong object is used. He used ```graph.getEdge("ab");``` to get the object "ab" from "graph", but when "graph" is cloned, "ab" got cloned as well. Thus, you can either use the id to identify "ab", or get the object from the new graph: 
```java
Edge edge = graph.getEdge("ab");

Graph tempGraph = Graphs.clone(graph);

Edge edgeClone = tempGraph.getEdge("ab");

tempGraph.removeEdge(edge);
graph.removeEdge(edgeClone);`
```
