### ISSUE TITLE
Sprites' ui.class is not always used

### ISSUE THREAD

**Issue by regan2** [graphstream/gs-core#325]
I tried to create several sprites, and gave each one a different class with the "ui.class" attribute. I found that only some of the sprites would use the style for their class, while the others fall back to the default sprite style.

My CSS looks like this:
```
        sprite {
           fill-color: red;
        }
        sprite.class1 {
           fill-color: blue;
        }
        sprite.class2 {
           fill-color: green;
        }
 ```
If I set
 `"ui.class": "class1"` 
or
 `"ui.class": "class2"` 
for every sprite, some of them will still show up red.

I found a way around this, by setting `ui.class` after the graph is already displayed.

This issue appears similar to #66, but I am using `GRAPH_IN_ANOTHER_THREAD`.

**Comment by hichbra** [comment]
Hi, 
I can't reproduce the issue, it work fin. If you found a way around then it's ok, but if you can provide us a simple and self contained example (SSCCE), that would be helpful.

**Comment by regan2** [comment]
Hi,
Thank you, I ended up realizing my error. I had downloaded GS 1.3 but set version 1.0 as a dependency in maven by accident. It works fine in 1.3 for me as well.
