### ISSUE TITLE
Mouseclick at wrong position in embedded javafx gui

### ISSUE THREAD

**Issue by N4tus** [graphstream/gs-core#335]
I am viewing a graph in javafx using the FxViewer to embed the canvas in an existing gui. However for an ui event (a mouse press event for example) on a node to be registered i need to click where the node would've been if the canvas was rendered at top-left 0-0.

**Comment by hichbra** [comment]
Hi!

This issue is related to https://github.com/graphstream/gs-ui-javafx/issues/21 I think. Can you try it ?

**Comment by N4tus** [comment]
Thank you for your fast response. That was indeed the problem and it works now like intended.
