### ISSUE TITLE
Deploy Maven source and javadoc artefacts to jitpack

### ISSUE THREAD

**Issue by victornoel** [graphstream/gs-core#336]
Currently the maven artefacts available from jitpack are only the binary jars, but during development using gs library, it is very useful to be able to also see the javadoc and browse the source code.

Hence it would make sense to deploy the Maven artefacts for sources and javadocs along with the jar.

See https://maven.apache.org/plugin-developers/cookbook/attach-source-javadoc-artifacts.html for example.

**Comment by pigne** [comment]
I tried something in this commit : 3416c141

Try it with the following dependency 

```xml
	<dependency>
	    <groupId>com.github.graphstream</groupId>
	    <artifactId>gs-core</artifactId>
	    <version>dev-SNAPSHOT</version>
	</dependency>
```

**Comment by victornoel** [comment]
@pigne nice, it seems to work as expected, could we also:
- add javadoc while we are at it
- do the same for the other modules

**Comment by pigne** [comment]
Sources and JavaDoc added to the build of each `gs-*` module:

- gs-core: 3416c141d01817e00f81b8c3e2da8ff520939232
- gs-algo: https://github.com/graphstream/gs-algo/commit/e3bae8d621367e391deabb822c05eda407152aa1
- gs-ui-javafx: https://github.com/graphstream/gs-ui-javafx/commit/6edf5312bfb378d3770956dac76380965bd5c9ef
- gs-ui-swing: https://github.com/graphstream/gs-ui-swing/commit/d31d2ee3623c2fd79df62bde8053c5fa2fc4b6e7

**Comment by victornoel** [comment]
@pigne really cool, thx :)
