### ISSUE TITLE
Viewer gets blanked when resizing.

### ISSUE THREAD

**Issue by glurquiaga** [graphstream/gs-core#342]
Hello. I have a Project with a graph viewer contained in an AnchorPane. When the AnchorPane is resized, the viewer gets blanked. If I click the mouse over the pane the graph appears again. How can I cause this automatically without having to click? Thanks in advanced.

**Comment by hichbra** [comment]
Check if you correctly refresh your view. If you build your own view, then you need to call ViewerPipe on a recurring basis as you can see in the [examples](https://github.com/graphstream/gs-ui-javafx/tree/2.0-alpha/src-test/org/graphstream/ui/viewer_fx/test).

**Comment by glurquiaga** [comment]
Finally I used a listener to anchorPane width and height property and when those change the display method of the view gets called. That solved it.
