### ISSUE TITLE
Using FileSinkImages / Tutorial

### ISSUE THREAD

**Issue by ghost** [graphstream/gs-core#356]
Hi,

FileSinkImages has changed (signature of constructor / now abstract class) and the tutorial 
https://graphstream-project.org/doc/Tutorials/Creating-a-movie-with-FileSinkImages/
is no longer correct. 

How to use FileSinkImages() (to create a set of .png files) now?

Cheers,  Ralf

**Comment by hichbra** [comment]
Hi, create a default and set up the parameters.
``` FileSinkImages fsi = FileSinkImages.createDefault(); ```
 You have an example at the bottom of the class. Other than that it work the same as the tutorial.

**Comment by ghost** [comment]
[FSIExample.zip](https://github.com/graphstream/gs-core/files/5746443/FSIExample.zip)
Hi, 

thanks for the fast reply. The instantiation works now but using it fails. I assume I use the sink the wrong way. The tutorial says its possible to use graphs "directly" (quote:"This source could be a graph for example, but it could be a generator, a dgs source, etc…"). So I added:

    graph.addSink(fsi);
    fsi.begin("picture_");

    // from "Getting started"
    Node n = graph.addNode("A");
    n.setAttribute("x", 100); n.setAttribute("y", 100);

    // Assumption see "Generators ..." - 
    fsi.nodeAdded("source1", 0, "A");
    // I parameterized   fsi.setOutputPolicy(FileSinkImages.OutputPolicy.BY_NODE_ADDED_REMOVED); 
    // assuming that it would create an event when this node is added 
    fsi.end();

BTW: I created a JavaFX Application to draw the graph because the "Getting Started" example fails with ...
Exception in thread "Thread-1" java.lang.NullPointerException: Cannot invoke "com.sun.glass.ui.Timer.resume()" because "this.pulseTimer" is null

I attached the example code (separated into two classes because of the module dependencies of JavaFX / extension of Application).

Do I need a DGS File as source? (And how to avoid the Nullpointer from "Getting Started"? 

Cheers,  Ralf

P.S. Sorry for mixing questions.

P.P.S. Is this the right forum for these kinds of questions?

**Comment by hichbra** [comment]
1/ Due to the nature of [```FxFileSinkImages```](https://github.com/graphstream/gs-ui-javafx/blob/2.0/src/org/graphstream/ui/javafx/util/FxFileSinkImages.java), you can't use it like that inside an Application, you should reimplement the class so it can run in the same thread. Here an working example outside of it : 
```java
public static void main(String[] args)
{
        // Tutorial 1
        System.setProperty("org.graphstream.ui", "javafx");
        Graph g = new SingleGraph("sg");
        
        // test to create images
        FileSinkImages fsi = FileSinkImages.createDefault();
        fsi.setOutputPolicy(FileSinkImages.OutputPolicy.BY_NODE_ADDED_REMOVED);
        fsi.setResolution(Resolutions.VGA);
        fsi.setOutputType(FileSinkImages.OutputType.PNG);

        g.addSink(fsi);

        try
        {
            fsi.begin("picture_");

            Node n = g.addNode("A");
            n.setAttribute("x", 100);
            n.setAttribute("y", 100);
            n = g.addNode("B");
            n.setAttribute("x", 0);
            n.setAttribute("y", 100);
            n = g.addNode("C");
            n.setAttribute("x", 100);
            n.setAttribute("y", 0);
            n = g.addNode("D");

            fsi.end();
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        finally
        {
            g.removeSink(fsi);
        }
        
        g.display();
}
```

2/ It can be related to [this](https://graphstream-project.org/doc/FAQ/The-graph-viewer/null-pointer-exeption-javafx/)

3/ Not really, this channel should be exclusively limited to the internal library issues.

**Comment by ghost** [comment]
Hi,

thanks again. I see. Unfortunately the error persists (in my environment) after setting the property.

Anything else missing? Is there another way?

![graphstreamDebug](https://user-images.githubusercontent.com/9784755/103403472-85d92700-4b50-11eb-9bc5-60577fbcfc5c.png)

Slowing something down (assumptions on system speed) seems a little "hacky" (hope I am not stepping on toes here - in general i like hacky and i really enjoy Graphstream ;)). 

Cheers & a happy new year, Ralf

P.S. I can switch to http://sympa.litislab.fr/sympa/info/graphstream-users (looks a little ... "old" regarding dialogs / sizes etc. and french came up first as default language - which i speak ... lets say very limited). 

But right now it seems to me that it's only partially a usage problem? Otherwise please tell me to leave :)

**Comment by hichbra** [comment]
Yes it's hacky because this issue is not supposed to happen outside the use of specific tools. There are something wrong with your JavaFX environment but I can't really help you more than that, I don't know what's wrong with your installation.

**Comment by ghost** [comment]
Thanks for the hint.

I checked my environment and it seems that the maven configuration did not add the fx modules automatically (as assumed) during runtime (https://openjfx.io/openjfx-docs/#maven). Manually adding them as vm option (https://openjfx.io/openjfx-docs/#install-javafx) did the trick.

Implementing an extra starter class that does not inherit from javafx.application.Application worked until I started to use FSISinkImages that needs to run in the same thread.
