### ISSUE TITLE
node shape: rounded-box not apply

### ISSUE THREAD

**Issue by rmaestre** [graphstream/gs-core#49]
Hi everyone, firstly: nice job with this library!!
However, with the next code i have one problem (using 1.1 libraries):

Node n = g.getNode(nodeLabel);
n.addAttribute("ui.style" , ("size: 10px, 10px; fill-color: #3d5689; shape: rounded-box; stroke-mode: plain; stroke-color: yellow;");
n.setAttribute("label",nodeLabel);

With the above code, nodes perform the change of size and fill-color well, but not shape, stroke-mode and stroke-color. In edges does not work shape forms.

Edge e = g.getEdge(from+to);
e.addAttribute("ui.style" , "cubic-curve;");

Any suggestion?
Best regards !

**Comment by yixuanhuangyx** [comment]
Hi there! 

I also got a question about the node shape.

I have gs-ui.jar in my classpath and this at the first line of my code:
 `System.setProperty("gs.ui.renderer", "org.graphstream.ui.j2dviewer.J2DGraphRenderer");`

Then I define a node:
`Node A = g.addNode("A");
A.setAttribute("ui.label", "Node A");
`
with the styleSheet like this:
` 
graph {padding:60px; fill-color: red;}
node {size-mode: fit; 
	  text-style: bold;
	  shape: rounded-box; 
	   fill-color: white; 
	   stroke-color: yellow; 
	   stroke-mode: plain; }
`
I want to get a reactangle shape of each node. but it only show up as a square. 
Except the node shape, the other properties are good.  

Any suggestion here?  :)

**Comment by vilimek-jakub** [comment]
> Hi there!
> 
> I also got a question about the node shape.
> 
> I have gs-ui.jar in my classpath and this at the first line of my code:
> `System.setProperty("gs.ui.renderer", "org.graphstream.ui.j2dviewer.J2DGraphRenderer");`
> 
> Then I define a node:
> `Node A = g.addNode("A"); A.setAttribute("ui.label", "Node A"); `
> with the styleSheet like this:
> ` graph {padding:60px; fill-color: red;} node {size-mode: fit; text-style: bold; shape: rounded-box; fill-color: white; stroke-color: yellow; stroke-mode: plain; }`
> I want to get a reactangle shape of each node. but it only show up as a square.
> Except the node shape, the other properties are good.
> 
> Any suggestion here? :)

I solved the same issue today. My bug was in gs-ui-javafx org.graphstream.ui.javafx.renderer.shape.javafx.Area
private void sizeForElement(Style style, DefaultCamera2D camera, GraphicElement element) {
...
if(style.getSize().size() > 1) 
h = camera.getMetrics().lengthToGu(style.getSize(), 1) ;
...
}

**Comment by hichbra** [comment]
This issue is already fixed https://github.com/graphstream/gs-ui-javafx/commit/bbea8a239686193a6f28a0d33e1dc872f8cd1398 and will be in the next release.

**Comment by vilimek-jakub** [comment]
Great, when will be the release ready? ;-)

**Comment by hichbra** [comment]
It depends on a lot of things, but I'm hoping it'll probably be done before the summer.
