### ISSUE TITLE
Modularity in Toolkit

### ISSUE THREAD

**Issue by sbalev** [graphstream/gs-core#60]
There is a bunch of methods dealing with modularity in Toolkit. There are several problems with them.

1. Their implementation is very inefficient. Basically, one can count the number of edges between _all_ the pairs of communities with _single_ iteration over the graph's edges. Thus the modularity can be found in linear O(m + n) time. The complexities announced in javadoc are even more frightening, it is a question about factorials!

2. (more serious) I think they are wrong. They tend to overestimate the real modularity. For example, for the following simple graph

```text
0           1
|\         /|
| 0---0---1 |
|/    |    \|
0     2     1
     / \
    2---2
```

`Toolkit.modularity(Graph, String)` reports `0.59375`. According to my own calculations, the modularity is `0.48958333` and according to [Wikipedia](http://en.wikipedia.org/wiki/Modularity_%28networks%29#Example_of_multiple_community_detection) it is `0.4985`. Who is right?

I think there is a bug in `Toolkit.modularity(double[][])` but for the moment I will not push a fix. I have to be sure that my way to compute works. Moreover, the methods try to handle _weightened_ modularity, which is a little bit more subtle.

**Comment by pigne** [comment]
Closing for it has been fixed by now.
