### ISSUE TITLE
Frame title

### ISSUE THREAD

**Issue by ktobah** [graphstream/gs-core#83]
Hello everybody;

I am having a small issue here, when I use GraphStream, I wrote this code : 

graph = new MultiGraph("Visualize Graph") ;

I would like the appeared frame to get the title "Visualize Graph", how can I do that ?

With the code above, all the time it shows the title "Graph Stream".

Thank you.

Best regards;
Ahmed.

**Comment by FrederikBolding** [comment]
To anyone curious who come from Google, this can be achieved using the attribute `ui.title`.

**Comment by gschurck** [comment]
It doesn't work for me

**Comment by rezamini** [comment]
> It doesn't work for me

You need to set it under graph attribute like:
graph.setAttribute("ui.title", "Your Title");
